### PR TITLE
adds listing listener and indexer

### PR DESCRIPTION
**Pull request by Gzing**
Have committed contract.json files directly into the repository now.
Will change once we have a better way to solve this.

Requirements
- [x] Must also work with local dev chains
- [x] Should store data in postgres
- [x] Should also store contract related IPFS in postgres so that both IPFS and contract data can be 
searched together.
 - [x] Records new Listings
 - [x] Records on Listing changes

### CODE REVIEW

**Comment by Gzing** [comment]
Thanks for checking this out @tyleryasaka. PR's would be feature specific going forward :+1: 
Will add some test cases/verify and push shortly.

**Comment by Gzing** [comment]
@tyleryasaka : I have update the branch. Have fixed the test issues and reduced the scope of the migrations as well.
Will be creating another issue to improve the test suite and make it easier. will add tests for indexer in that branch.
Please see if you can approve this one.

**Comment by Gzing** [comment]
> @Gzing Still getting test failures.
Sorry to waste your time on this. Would it be possible for you to shed more light on what test is failing or the error log? It runs fine on my local, maybe I am missing something.

> Also, I think we need to go ahead and add the tests in this PR - saying we will do them later is the best way to never do them smiley. Some basic testing for the indexer will need to be there before I can approve.
The reason to not add tests in this one was not slacking off, but wanted to align the test framework and settings to the PR https://github.com/OriginProtocol/company-website/pull/151, so that both `bridge-server` and `company-website` are functionally similar and we get the benefits that `pytest` offers.
Anyways, adding tests with the current settings to this branch now

**Comment by ambertch** [comment]
#4

**Pull request merged**
