### PR TITLE
integrates pytest

### PR DESCRIPTION
**Pull request by Gzing**
### Checklist:

- [x] Code contains relevant tests for the problem you are solving
- [x] Ensure all new and existing tests pass
- [x] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)
- [x] Submit to the `develop` branch instead of `master`

### Description:

Please explain the changes you made here:

- Move away from unittest and integrate with pytest
- The only change to the end user is to use `pytest --flakes` to run the tests instead of the earlier command `python testing/all_tests.py`
- The benefits are:
   1. `company-website` and `bridge-server` would have same test frameworks in place, making easier developer onboarding
   2. Richer features than unittest and a lot of community packages/recipes

### CODE REVIEW

**Comment by tyleryasaka** [comment]
Also, please make smaller commits.

**Comment by Gzing** [comment]
@tyleryasaka, thanks for checking this out.
> The README setup instructions need to include pip install -U pytest. Other wise the test command doesn't work.

We don't need an explicit install for pytest, user should just do `pip install -r requirements.txt` when setting up the project and that would take care of pytest or any other packages.

> The tests aren't passing for me. I'm getting the error below:

The issue here was a malformed package requirement which I have corrected:
screenshot from 2018-04-23 12-00-40


> Also, please make smaller commits.

:+1:

**Comment by tyleryasaka** [comment]
> We don't need an explicit install for pytest, user should just do pip install -r requirements.txt when setting up the project and that would take care of pytest or any other packages.

Ah - I had to explicitly run the command even after `pip install -r requirements.txt` - but that was because of the typo that you fixed. It works now. 👍 

This looks good to me.

We actually just enabled Travis CI on this repository but the tests on this PR are failing because there is no `.travis.yml` file. Can you add it?

See this commit: https://github.com/OriginProtocol/bridge-server/commit/6a1abf7123e89aafe04dc33eff0001409e17c281

**Comment by Gzing** [comment]
Sure, on it. Thanks for adding Travis over Codeship :+1: :+1:

**Pull request merged**
